# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '微信发现界面' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 微信发现界面
pod 'ReactiveObjC', '~> 3.1.0'
end
