source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target ‘SimpleWeather’ do
pod 'Mantle' ,'~>1.3.1'
pod 'LBBlurredImage','~>0.1.0'
pod 'TSMessages','~>0.9.4'
pod 'ReactiveCocoa','~>2.1.7'
pod 'AFNetworking', '~> 3.0'
end

